# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindowyahtzee.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 805)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_roll_dice = QtWidgets.QPushButton(self.centralwidget)
        self.button_roll_dice.setGeometry(QtCore.QRect(20, 630, 71, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.button_roll_dice.setFont(font)
        self.button_roll_dice.setStyleSheet("background-color: rgb(255, 38, 40);")
        self.button_roll_dice.setObjectName("button_roll_dice")
        self.label_die_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_die_1.setGeometry(QtCore.QRect(110, 640, 81, 71))
        self.label_die_1.setMaximumSize(QtCore.QSize(81, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_die_1.setFont(font)
        self.label_die_1.setStyleSheet("")
        self.label_die_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_die_1.setText("")
        self.label_die_1.setScaledContents(True)
        self.label_die_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_die_1.setObjectName("label_die_1")
        self.label_die_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_die_2.setGeometry(QtCore.QRect(210, 640, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_die_2.setFont(font)
        self.label_die_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_die_2.setText("")
        self.label_die_2.setScaledContents(True)
        self.label_die_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_die_2.setObjectName("label_die_2")
        self.label_die_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_die_3.setGeometry(QtCore.QRect(310, 640, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_die_3.setFont(font)
        self.label_die_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_die_3.setText("")
        self.label_die_3.setScaledContents(True)
        self.label_die_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_die_3.setObjectName("label_die_3")
        self.label_die_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_die_4.setGeometry(QtCore.QRect(410, 640, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_die_4.setFont(font)
        self.label_die_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_die_4.setText("")
        self.label_die_4.setScaledContents(True)
        self.label_die_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_die_4.setObjectName("label_die_4")
        self.label_die_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_die_5.setGeometry(QtCore.QRect(510, 640, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_die_5.setFont(font)
        self.label_die_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_die_5.setText("")
        self.label_die_5.setScaledContents(True)
        self.label_die_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_die_5.setObjectName("label_die_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 30, 111, 541))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 0, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(460, 30, 121, 551))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(450, 0, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_box_total_lower = QtWidgets.QLabel(self.centralwidget)
        self.label_box_total_lower.setGeometry(QtCore.QRect(590, 420, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_box_total_lower.setFont(font)
        self.label_box_total_lower.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_box_total_lower.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_box_total_lower.setText("")
        self.label_box_total_lower.setAlignment(QtCore.Qt.AlignCenter)
        self.label_box_total_lower.setObjectName("label_box_total_lower")
        self.button_aces = QtWidgets.QPushButton(self.centralwidget)
        self.button_aces.setGeometry(QtCore.QRect(230, 30, 51, 41))
        self.button_aces.setText("")
        self.button_aces.setObjectName("button_aces")
        self.button_full_house = QtWidgets.QPushButton(self.centralwidget)
        self.button_full_house.setGeometry(QtCore.QRect(660, 120, 51, 41))
        self.button_full_house.setText("")
        self.button_full_house.setObjectName("button_full_house")
        self.button_4_of_a_kind = QtWidgets.QPushButton(self.centralwidget)
        self.button_4_of_a_kind.setGeometry(QtCore.QRect(660, 70, 51, 41))
        self.button_4_of_a_kind.setText("")
        self.button_4_of_a_kind.setObjectName("button_4_of_a_kind")
        self.button_twos = QtWidgets.QPushButton(self.centralwidget)
        self.button_twos.setGeometry(QtCore.QRect(230, 90, 51, 41))
        self.button_twos.setText("")
        self.button_twos.setObjectName("button_twos")
        self.button_lg_straight = QtWidgets.QPushButton(self.centralwidget)
        self.button_lg_straight.setGeometry(QtCore.QRect(660, 220, 51, 41))
        self.button_lg_straight.setText("")
        self.button_lg_straight.setObjectName("button_lg_straight")
        self.button_yahtzee_bonus = QtWidgets.QPushButton(self.centralwidget)
        self.button_yahtzee_bonus.setGeometry(QtCore.QRect(660, 360, 51, 41))
        self.button_yahtzee_bonus.setText("")
        self.button_yahtzee_bonus.setObjectName("button_yahtzee_bonus")
        self.button_chance = QtWidgets.QPushButton(self.centralwidget)
        self.button_chance.setGeometry(QtCore.QRect(660, 310, 51, 41))
        self.button_chance.setText("")
        self.button_chance.setObjectName("button_chance")
        self.button_yahtzee = QtWidgets.QPushButton(self.centralwidget)
        self.button_yahtzee.setGeometry(QtCore.QRect(660, 270, 51, 41))
        self.button_yahtzee.setText("")
        self.button_yahtzee.setObjectName("button_yahtzee")
        self.button_3_of_a_kind = QtWidgets.QPushButton(self.centralwidget)
        self.button_3_of_a_kind.setGeometry(QtCore.QRect(660, 20, 51, 41))
        self.button_3_of_a_kind.setText("")
        self.button_3_of_a_kind.setObjectName("button_3_of_a_kind")
        self.button_threes = QtWidgets.QPushButton(self.centralwidget)
        self.button_threes.setGeometry(QtCore.QRect(230, 160, 51, 41))
        self.button_threes.setText("")
        self.button_threes.setObjectName("button_threes")
        self.button_fours = QtWidgets.QPushButton(self.centralwidget)
        self.button_fours.setGeometry(QtCore.QRect(230, 220, 51, 41))
        self.button_fours.setText("")
        self.button_fours.setObjectName("button_fours")
        self.button_fives = QtWidgets.QPushButton(self.centralwidget)
        self.button_fives.setGeometry(QtCore.QRect(230, 280, 51, 41))
        self.button_fives.setText("")
        self.button_fives.setObjectName("button_fives")
        self.button_sixes = QtWidgets.QPushButton(self.centralwidget)
        self.button_sixes.setGeometry(QtCore.QRect(230, 340, 51, 41))
        self.button_sixes.setText("")
        self.button_sixes.setObjectName("button_sixes")
        self.button_sm_straight = QtWidgets.QPushButton(self.centralwidget)
        self.button_sm_straight.setGeometry(QtCore.QRect(660, 170, 51, 41))
        self.button_sm_straight.setText("")
        self.button_sm_straight.setObjectName("button_sm_straight")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(590, 30, 61, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_11.setObjectName("label_11")
        self.label_box_grand_total = QtWidgets.QLabel(self.centralwidget)
        self.label_box_grand_total.setGeometry(QtCore.QRect(590, 520, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_box_grand_total.setFont(font)
        self.label_box_grand_total.setStyleSheet("background-color: rgb(56, 255, 49);")
        self.label_box_grand_total.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_box_grand_total.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_box_grand_total.setText("")
        self.label_box_grand_total.setAlignment(QtCore.Qt.AlignCenter)
        self.label_box_grand_total.setObjectName("label_box_grand_total")
        self.label_box_total_upper_repeat = QtWidgets.QLabel(self.centralwidget)
        self.label_box_total_upper_repeat.setGeometry(QtCore.QRect(590, 470, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_box_total_upper_repeat.setFont(font)
        self.label_box_total_upper_repeat.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_box_total_upper_repeat.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_box_total_upper_repeat.setText("")
        self.label_box_total_upper_repeat.setAlignment(QtCore.Qt.AlignCenter)
        self.label_box_total_upper_repeat.setObjectName("label_box_total_upper_repeat")
        self.label_box_total_upper = QtWidgets.QLabel(self.centralwidget)
        self.label_box_total_upper.setGeometry(QtCore.QRect(230, 520, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_box_total_upper.setFont(font)
        self.label_box_total_upper.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_box_total_upper.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_box_total_upper.setText("")
        self.label_box_total_upper.setAlignment(QtCore.Qt.AlignCenter)
        self.label_box_total_upper.setObjectName("label_box_total_upper")
        self.label_box_bonus = QtWidgets.QLabel(self.centralwidget)
        self.label_box_bonus.setGeometry(QtCore.QRect(230, 470, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_box_bonus.setFont(font)
        self.label_box_bonus.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_box_bonus.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_box_bonus.setText("")
        self.label_box_bonus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_box_bonus.setObjectName("label_box_bonus")
        self.label_box_total_score = QtWidgets.QLabel(self.centralwidget)
        self.label_box_total_score.setGeometry(QtCore.QRect(230, 420, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_box_total_score.setFont(font)
        self.label_box_total_score.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_box_total_score.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_box_total_score.setText("")
        self.label_box_total_score.setAlignment(QtCore.Qt.AlignCenter)
        self.label_box_total_score.setObjectName("label_box_total_score")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(140, 30, 81, 361))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(160, 470, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_score_aces = QtWidgets.QLabel(self.centralwidget)
        self.label_score_aces.setGeometry(QtCore.QRect(230, 30, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_score_aces.setFont(font)
        self.label_score_aces.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_score_aces.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_score_aces.setText("")
        self.label_score_aces.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_aces.setObjectName("label_score_aces")
        self.label_warning = QtWidgets.QLabel(self.centralwidget)
        self.label_warning.setGeometry(QtCore.QRect(310, 120, 121, 211))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_warning.setFont(font)
        self.label_warning.setFrameShape(QtWidgets.QFrame.Box)
        self.label_warning.setText("")
        self.label_warning.setAlignment(QtCore.Qt.AlignCenter)
        self.label_warning.setObjectName("label_warning")
        self.label_score_twos = QtWidgets.QLabel(self.centralwidget)
        self.label_score_twos.setGeometry(QtCore.QRect(230, 90, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_score_twos.setFont(font)
        self.label_score_twos.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_score_twos.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_score_twos.setText("")
        self.label_score_twos.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_twos.setObjectName("label_score_twos")
        self.label_score_threes = QtWidgets.QLabel(self.centralwidget)
        self.label_score_threes.setGeometry(QtCore.QRect(230, 160, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_score_threes.setFont(font)
        self.label_score_threes.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_score_threes.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_score_threes.setText("")
        self.label_score_threes.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_threes.setObjectName("label_score_threes")
        self.label_score_fives = QtWidgets.QLabel(self.centralwidget)
        self.label_score_fives.setGeometry(QtCore.QRect(230, 290, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_score_fives.setFont(font)
        self.label_score_fives.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_score_fives.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_score_fives.setText("")
        self.label_score_fives.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_fives.setObjectName("label_score_fives")
        self.label_score_fours = QtWidgets.QLabel(self.centralwidget)
        self.label_score_fours.setGeometry(QtCore.QRect(230, 230, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_score_fours.setFont(font)
        self.label_score_fours.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_score_fours.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_score_fours.setText("")
        self.label_score_fours.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_fours.setObjectName("label_score_fours")
        self.label_score_sixes = QtWidgets.QLabel(self.centralwidget)
        self.label_score_sixes.setGeometry(QtCore.QRect(230, 350, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_score_sixes.setFont(font)
        self.label_score_sixes.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_score_sixes.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_score_sixes.setText("")
        self.label_score_sixes.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_sixes.setObjectName("label_score_sixes")
        self.label_score_3_of_a_kind = QtWidgets.QLabel(self.centralwidget)
        self.label_score_3_of_a_kind.setGeometry(QtCore.QRect(660, 30, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_score_3_of_a_kind.setFont(font)
        self.label_score_3_of_a_kind.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_score_3_of_a_kind.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_score_3_of_a_kind.setText("")
        self.label_score_3_of_a_kind.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_3_of_a_kind.setObjectName("label_score_3_of_a_kind")
        self.label_score_4_of_a_kind = QtWidgets.QLabel(self.centralwidget)
        self.label_score_4_of_a_kind.setGeometry(QtCore.QRect(660, 80, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_score_4_of_a_kind.setFont(font)
        self.label_score_4_of_a_kind.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_score_4_of_a_kind.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_score_4_of_a_kind.setText("")
        self.label_score_4_of_a_kind.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_4_of_a_kind.setObjectName("label_score_4_of_a_kind")
        self.label_score_full_house = QtWidgets.QLabel(self.centralwidget)
        self.label_score_full_house.setGeometry(QtCore.QRect(660, 130, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_score_full_house.setFont(font)
        self.label_score_full_house.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_score_full_house.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_score_full_house.setText("")
        self.label_score_full_house.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_full_house.setObjectName("label_score_full_house")
        self.label_score_sm_straight = QtWidgets.QLabel(self.centralwidget)
        self.label_score_sm_straight.setGeometry(QtCore.QRect(660, 180, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_score_sm_straight.setFont(font)
        self.label_score_sm_straight.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_score_sm_straight.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_score_sm_straight.setText("")
        self.label_score_sm_straight.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_sm_straight.setObjectName("label_score_sm_straight")
        self.label_score_lg_straight = QtWidgets.QLabel(self.centralwidget)
        self.label_score_lg_straight.setGeometry(QtCore.QRect(660, 230, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_score_lg_straight.setFont(font)
        self.label_score_lg_straight.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_score_lg_straight.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_score_lg_straight.setText("")
        self.label_score_lg_straight.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_lg_straight.setObjectName("label_score_lg_straight")
        self.label_score_yahtzee = QtWidgets.QLabel(self.centralwidget)
        self.label_score_yahtzee.setGeometry(QtCore.QRect(660, 280, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_score_yahtzee.setFont(font)
        self.label_score_yahtzee.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_score_yahtzee.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_score_yahtzee.setText("")
        self.label_score_yahtzee.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_yahtzee.setObjectName("label_score_yahtzee")
        self.label_score_chance = QtWidgets.QLabel(self.centralwidget)
        self.label_score_chance.setGeometry(QtCore.QRect(660, 320, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_score_chance.setFont(font)
        self.label_score_chance.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_score_chance.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_score_chance.setText("")
        self.label_score_chance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_chance.setObjectName("label_score_chance")
        self.label_score_yahtzee_bonus = QtWidgets.QLabel(self.centralwidget)
        self.label_score_yahtzee_bonus.setGeometry(QtCore.QRect(660, 370, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_score_yahtzee_bonus.setFont(font)
        self.label_score_yahtzee_bonus.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_score_yahtzee_bonus.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_score_yahtzee_bonus.setText("")
        self.label_score_yahtzee_bonus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_yahtzee_bonus.setObjectName("label_score_yahtzee_bonus")
        self.button_new_game = QtWidgets.QPushButton(self.centralwidget)
        self.button_new_game.setGeometry(QtCore.QRect(770, 670, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.button_new_game.setFont(font)
        self.button_new_game.setObjectName("button_new_game")
        self.button_die_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_die_1.setGeometry(QtCore.QRect(110, 580, 81, 41))
        self.button_die_1.setCheckable(True)
        self.button_die_1.setObjectName("button_die_1")
        self.button_die_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_die_2.setGeometry(QtCore.QRect(210, 580, 81, 41))
        self.button_die_2.setCheckable(True)
        self.button_die_2.setObjectName("button_die_2")
        self.button_die_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_die_3.setGeometry(QtCore.QRect(310, 580, 81, 41))
        self.button_die_3.setCheckable(True)
        self.button_die_3.setObjectName("button_die_3")
        self.button_die_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_die_4.setGeometry(QtCore.QRect(410, 580, 81, 41))
        self.button_die_4.setCheckable(True)
        self.button_die_4.setObjectName("button_die_4")
        self.button_die_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_die_5.setGeometry(QtCore.QRect(510, 580, 81, 41))
        self.button_die_5.setCheckable(True)
        self.button_die_5.setObjectName("button_die_5")
        self.label_keep_die_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_keep_die_2.setGeometry(QtCore.QRect(210, 650, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_keep_die_2.setFont(font)
        self.label_keep_die_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_keep_die_2.setText("")
        self.label_keep_die_2.setScaledContents(True)
        self.label_keep_die_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keep_die_2.setObjectName("label_keep_die_2")
        self.label_keep_die_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_keep_die_3.setGeometry(QtCore.QRect(310, 650, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_keep_die_3.setFont(font)
        self.label_keep_die_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_keep_die_3.setText("")
        self.label_keep_die_3.setScaledContents(True)
        self.label_keep_die_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keep_die_3.setObjectName("label_keep_die_3")
        self.label_keep_die_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_keep_die_4.setGeometry(QtCore.QRect(410, 650, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_keep_die_4.setFont(font)
        self.label_keep_die_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_keep_die_4.setText("")
        self.label_keep_die_4.setScaledContents(True)
        self.label_keep_die_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keep_die_4.setObjectName("label_keep_die_4")
        self.label_keep_die_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_keep_die_5.setGeometry(QtCore.QRect(510, 650, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_keep_die_5.setFont(font)
        self.label_keep_die_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_keep_die_5.setText("")
        self.label_keep_die_5.setScaledContents(True)
        self.label_keep_die_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keep_die_5.setObjectName("label_keep_die_5")
        self.label_keep_die_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_keep_die_1.setGeometry(QtCore.QRect(110, 650, 81, 71))
        self.label_keep_die_1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_keep_die_1.setText("")
        self.label_keep_die_1.setScaledContents(True)
        self.label_keep_die_1.setObjectName("label_keep_die_1")
        self.button_choose_zero_score = QtWidgets.QPushButton(self.centralwidget)
        self.button_choose_zero_score.setGeometry(QtCore.QRect(740, 570, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.button_choose_zero_score.setFont(font)
        self.button_choose_zero_score.setObjectName("button_choose_zero_score")
        self.label_instructions = QtWidgets.QLabel(self.centralwidget)
        self.label_instructions.setGeometry(QtCore.QRect(710, 450, 151, 71))
        self.label_instructions.setAlignment(QtCore.Qt.AlignCenter)
        self.label_instructions.setObjectName("label_instructions")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(700, 520, 171, 32))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 874, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YAHTZEE!"))
        self.button_roll_dice.setText(_translate("MainWindow", "Roll\n"
"the\n"
"dice"))
        self.label_7.setText(_translate("MainWindow", "Aces = 1\n"
"\n"
"\n"
"\n"
"Twos = 2\n"
"\n"
"\n"
"\n"
"Threes = 3\n"
"\n"
"\n"
"\n"
"Fours = 4\n"
"\n"
"\n"
"\n"
"Fives = 5\n"
"\n"
"\n"
"\n"
"Sixes = 6\n"
"\n"
"_______________\n"
"\n"
"\n"
"TOTAL SCORE\n"
"\n"
"\n"
"BONUS\n"
"(Total 63 or over)\n"
"\n"
"TOTAL UPPER\n"
"SECTION"))
        self.label_8.setText(_translate("MainWindow", "SCORING UPPER SECTION:"))
        self.label_9.setText(_translate("MainWindow", "3 of a kind\n"
"\n"
"\n"
"4 of a kind\n"
"\n"
"\n"
"Full House\n"
"\n"
"\n"
"Small Straight\n"
"      Seq of 4\n"
"\n"
"Large Straight\n"
"      Seq of 5\n"
"\n"
"YAHTZEE\n"
"      5 of a kind\n"
"\n"
"Chance\n"
"\n"
"\n"
"YAHTZEE BONUS\n"
"\n"
"\n"
"\n"
"Total lower section\n"
"\n"
"\n"
"Total upper section\n"
"\n"
"\n"
"GRAND TOTAL"))
        self.label_10.setText(_translate("MainWindow", "SCORING LOWER SECTION:"))
        self.label_11.setText(_translate("MainWindow", "Add Total\n"
"Of All Dice\n"
"\n"
"\n"
"Add Total\n"
"Of All Dice\n"
"\n"
"\n"
"\n"
"SCORE 25\n"
"\n"
"\n"
"\n"
"SCORE 30\n"
"\n"
"\n"
"\n"
"SCORE 40\n"
"\n"
"\n"
"\n"
"SCORE 50\n"
"\n"
"\n"
"Score Total\n"
"Of All 5 Dice\n"
"\n"
"\n"
"SCORE 100\n"
"Per Bonus"))
        self.label_12.setText(_translate("MainWindow", "Count and Add\n"
"Only Aces\n"
"\n"
"\n"
"\n"
"Count and Add\n"
"Only Twos\n"
"\n"
"\n"
"\n"
"Count and Add\n"
"Only Threes\n"
"\n"
"\n"
"\n"
"Count and Add\n"
"Only Fours\n"
"\n"
"\n"
"\n"
"Count and Add\n"
"Only Fives\n"
"\n"
"\n"
"\n"
"Count and Add\n"
"Only Sixes"))
        self.label_13.setText(_translate("MainWindow", "SCORE 35"))
        self.button_new_game.setText(_translate("MainWindow", "NEW\n"
"GAME"))
        self.button_die_1.setText(_translate("MainWindow", "Save"))
        self.button_die_2.setText(_translate("MainWindow", "Save"))
        self.button_die_3.setText(_translate("MainWindow", "Save"))
        self.button_die_4.setText(_translate("MainWindow", "Save"))
        self.button_die_5.setText(_translate("MainWindow", "Save"))
        self.button_choose_zero_score.setText(_translate("MainWindow", "Select"))
        self.label_instructions.setText(_translate("MainWindow", "Select which category is\n"
"to be a zero score and\n"
"hit Select if you don\'t\n"
"have a play"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Aces"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Twos"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Threes"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Fours"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Fives"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Sixes"))
        self.comboBox.setItemText(6, _translate("MainWindow", "3 of a kind"))
        self.comboBox.setItemText(7, _translate("MainWindow", "4 of a kind"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Full House"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Small Straight"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Large Straight"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Yahtzee"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Chance"))
        self.comboBox.setItemText(13, _translate("MainWindow", "Yahtzee Bonus"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
